{
 "title": "TAP monitoring Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TAP Infrastructure Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Package Repositories",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "carvel_packagerepository_info{namespace=\"tanzu-package-repo-global\",type=\"ReconcileSucceeded\",status=\"True\"}",
       "legendFormat": "{{oci_image}}"
      }
     ]
    },
    {
     "title": "TAP Package Installs",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "carvel_packageinstall_info{namespace=\"tap-install\",type=\"ReconcileSucceeded\",status=\"True\"}",
       "legendFormat": "{{package_name}}"
      }
     ]
    },
    {
     "title": "Developer Namespaces",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "carvel_app_namespaces{namespace=\"tap-namespace-provisioning\",name=\"provisioner\"}",
       "legendFormat": "{{namespaces_deployed_to}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tanzu Build Service Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Workloads Using Each Buildpack",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (id) (topk(1000, count by (id, workload) (kpack_build_involved_buildpacks)))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Successful Builds Per Workload",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (workload) (kpack_build_status{status=\"True\", type=\"Succeeded\"})",
       "legendFormat": "{{workload}}"
      }
     ]
    },
    {
     "title": "Failed Builds Per Workload",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (workload) (kpack_build_status{status=\"Failed\", type=\"Succeeded\"})",
       "legendFormat": "{{workload}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workload Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workloads Without A Matching Supply Chain",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "cartographer_workload_status{type=\"SupplyChainReady\",status=\"False\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workloads in a Failed State",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "cartographer_workload_status{type=\"Ready\",status=\"False\"}",
       "legendFormat": "{{workload}}"
      }
     ]
    },
    {
     "title": "Workloads with Latest Revision Not Ready",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "count by (workload) (knative_service_info unless ignoring(dst) (label_replace(knative_service_info, \"dst\", \"$1\", \"latest_created_revision\", \"(.*)\") == label_replace(knative_service_info, \"dst\", \"$1\", \"latest_ready_revision\", \"(.*)\")))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Workloads Per Workload Type",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 34 },
     "targets": [
      {
       "expr": "count by (type) (cartographer_workload_info)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Number of Workloads Per Supply Chain",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "count by (supply_chain) (cartographer_workload_info)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Number of Workloads Per Source Type",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "count(cartographer_workload_info{source_image=\"\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(cartographer_workload_info{source_git_url=\"\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workloads With Live Update Enabled",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": " cartographer_workload_info{live_update_enabled=\"true\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Workloads Without Live Update Enabled",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": " (cartographer_workload_info{live_update_enabled=\"false\"} or cartographer_workload_info{live_update_enabled=\"\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Workloads With Remote Debug Enabled",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "cartographer_workload_info{debug_enabled=\"true\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Workloads Without Remote Debug Enabled",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "targets": [
      {
       "expr": "cartographer_workload_info{debug_enabled=\"false\"} or cartographer_workload_info{debug_enabled=\"\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Source Controller Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Code Source Retriever Per Workload",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "flux_git_repository_status{type=\"Ready\",owner_type=\"Workload\",component=\"source\",status=\"True\"}",
       "legendFormat": "{{workload}}"
      }
     ]
    },
    {
     "title": "Failed Source Code Retriever Per Workload",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "flux_git_repository_status{type=\"Ready\",owner_type=\"Workload\",component=\"source\",status=\"False\"}",
       "legendFormat": "{{workload}}"
      }
     ]
    },
    {
     "title": "Successful Delivery.yml Retriever Per Deliverable",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
     "targets": [
      {
       "expr": "flux_git_repository_status{type=\"Ready\",owner_type=\"Deliverable\",component=\"source\",status=\"True\"}",
       "legendFormat": "{{workload}}"
      }
     ]
    },
    {
     "title": "Failed Delivery.yml Retriever Per Deliverable",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 124 },
     "targets": [
      {
       "expr": "flux_git_repository_status{type=\"Ready\",owner_type=\"Deliverable\",component=\"source\",status=\"False\"}",
       "legendFormat": "{{workload}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tekton Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Testing Pipeline Runs Per Workload",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "count by (workload) (tekton_pipeline_run_status{type=\"Succeeded\",status=\"True\"})",
       "legendFormat": "{{workload}}"
      }
     ]
    },
    {
     "title": "Failed Testing Pipeline Runs Per Workload",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "count by (workload) (tekton_pipeline_run_status{type=\"Succeeded\",status=\"False\"})",
       "legendFormat": "{{workload}}"
      }
     ]
    },
    {
     "title": "Successful Config Writer Tasks Per Workload",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "count by (workload) (tekton_task_run_status{component=\"config-writer\",type=\"Succeeded\",status=\"True\"})",
       "legendFormat": "{{workload}}"
      }
     ]
    },
    {
     "title": "Failed Config Writer Tasks Per Workload",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "count by (workload) (tekton_task_run_status{component=\"config-writer\",type=\"Succeeded\",status=\"False\"})",
       "legendFormat": "{{workload}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scanning Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scanning Package Installation",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "carvel_packageinstall_info{namespace=\"tap-install\",type=\"ReconcileSucceeded\",status=\"True\",name=\"grype\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Source Scan Results Per Workload",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      { "expr": "scst_source_scan_status{}", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Image Scan Results Per Workload",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "targets": [
      { "expr": "scst_image_scan_status{}", "legendFormat": "{{name}}" }
     ]
    }
   ]
  },
  {
   "title": "Accelerators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accelerators",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 153 },
     "targets": [
      {
       "expr": "accelerator_info{ready=\"true\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Fragments",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 161 },
     "targets": [
      {
       "expr": "accelerator_fragment_info{ready=\"true\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Knative Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Knative Services",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "targets": [
      { "expr": "knative_service_info{}", "legendFormat": "{{workload}}" }
     ]
    },
    {
     "title": "Knative Services in Bad State",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "knative_service_status{status=\"False\",type=\"Ready\"}",
       "legendFormat": "{{workload}}"
      }
     ]
    },
    {
     "title": "Knative Services With Latest Revision Not Ready",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "knative_service_info unless ignoring(dst) (label_replace(knative_service_info, \"dst\", \"$1\", \"latest_created_revision\", \"(.*)\") == label_replace(knative_service_info, \"dst\", \"$1\", \"latest_ready_revision\", \"(.*)\"))",
       "legendFormat": "{{workload}}"
      }
     ]
    },
    {
     "title": "Failed Knative Revisions",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "knative_revision_status{status=\"False\",type=\"Ready\"}",
       "legendFormat": "{{workload}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Deliverables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deliverables in Failed State",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "cartographer_deliverable_status{type=\"Ready\",status=\"False\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Deliverables in Successful State",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "cartographer_deliverable_status{type=\"Ready\",status=\"True\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Number of Deliverables Per Source Type",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 22 },
     "targets": [
      {
       "expr": "count(cartographer_deliverable_info{source_image=\"\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(cartographer_deliverable_info{source_git_url=\"\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Bindings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Instance Classes",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "stk_cluster_instance_class_status{type=\"Ready\",status=\"True\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}